### ISSUE TITLE
Deletion of some uncessary file

### ISSUE THREAD

**Issue by csasm** [rauljim/pymdht#20]
i have looked into core, plugins, profiler, ui, ut2mdht. Each of the directories contains **init**.py file. but its empty. Please have a look at it and comment

**Comment by rauljim** [comment]
I don't see the problem. Your develop branch (just pulled from mine) contains an ui directory with files in it.
https://github.com/csasm/pymdht/tree/develop/ui

**Comment by csasm** [comment]
My develop branch file

https://github.com/csasm/pymdht/tree/develop/ui/__init__.py is empty.

also you branch file

https://github.com/rauljim/pymdht/tree/develop/ui/__init__.py is empty.

**Comment by rauljim** [comment]
Oh, I thought you meant the /directory/ was empty. The **init**.py files are necessary and they are commonly empty. You can test it yourself. If you remove the ui/**init**.py file, interactive_dht.py won't work.

See http://docs.python.org/tutorial/modules.html#packages
"The **init**.py files are required to make Python treat the directories as containing packages; this is done to prevent directories with a common name, such as string, from unintentionally hiding valid modules that occur later on the module search path. In the simplest case, **init**.py can just be an empty file, but it can also execute initialization code for the package or set the **all** variable, described later."

I think that closes this issue. You can close it.

**Comment by csasm** [comment]
Thanks. I got it now
