### ISSUE TITLE
Timeouts in graphical display

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#21]
Timeout nodes show in red immediately.

I think it's better to show them on yellow for 2 seconds and then red. That way, yellow nodes represent the number of parallel queries at any moment in time.

**Comment by csasm** [comment]
This has also been implemented.Please check the latest version

**Comment by csasm** [comment]
The problem is now when i select option of having display in slow motion with factor x
1. When slow factor x = 1 then the time out for a node is 2 second
2. When slow factor x = 10 then the time out for node is 20 second
So on ................
Please suggest some useful tip

**Comment by rauljim** [comment]
We can take a look at it today.

**Comment by csasm** [comment]
I have done it and also noted the time.Please let me know if its having some problem

**Comment by csasm** [comment]
I have done it and also checked the time it takes.U also please check it.

**Comment by rauljim** [comment]
Red nodes should only show after 2 seconds of that node being yellow. It doesn't make sense that a red node shows up before 2 seconds into the lookup.

**Comment by csasm** [comment]
This problem has been solved, please check and confirm

**Comment by rauljim** [comment]
Yes, now it looks much better.
