### ISSUE TITLE
Rename interactive_dht.py

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#23]
interactive_dht.py has grown quite a lot. Now it can do GUI and run on daemon mode (no interactivity), so the name is not appropriate anymore.

Suggestions:
pymdht_node.py

**Comment by rizvisarwar** [comment]
It can be:
1. run_pymdht_node.py
2. run_dht_node.py
3. dht_node.py
4. new_pymdht_node.py
5. launch_pymdht_node.py

**Comment by rauljim** [comment]
Thanks for the suggestions.
My favorite so far:
pymdht_node.py
run_pymdht_node.py

I reopen the issue (it's not close until we actually change the name in the code).

**Comment by zinat** [comment]
I vote for 
1. run_pymdht_node.py
2.launch_pymdht_node.py

**Comment by rauljim** [comment]
Renamed to run_pymdht_node.py in version 12.1.0
