### ISSUE TITLE
Time clock on graphical display

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#25]
Show current time/total time. Example: 1.2345/7.826

**Comment by csasm** [comment]
I have implemented it, please check and provide feedback if it is ok

**Comment by rauljim** [comment]
It looks very good.

Two details:
- Maybe it's better to have the timer in milliseconds?
- I'd like to see the total time, I think it's useful info. Example: 1.234/7.826
- The user can move the bar. I think that the user would expect that the display corresponds to that. So if the user moves the bar, the nodes display should move to the new timestamp.
  I'm not saying you implement this (although might be cool) but if you don't want to interact with the user, you should use a progress bar the user cannot play with.

**Comment by csasm** [comment]
I have incorporated total time also i have converted to progressbar.
Timer in design as in textual grid is in seconds so its better to be conformant with design and keep it in seconds in progressbar also.

**Comment by rauljim** [comment]
The progress bar does not show real-time information.
I remember you saying it represented progress in number of steps, that would be misleading.

**Comment by csasm** [comment]
Now it is showing real time propagation instead of step wise propagation

**Comment by rauljim** [comment]
OK, I think it's good enough. It would be more 'natural' if the progress bar moved smoothly instead of jumping.
