### ISSUE TITLE
Info_hash selector in graphical display

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#28]
This is more a question rather than an issue.

In the graphical display, when I select a file, I have the option to select an info_hash. But I always have files with a single info_hash each (saved by the interactive_dht GUI).
- Wouldn't it good to select the info_hash by default instead of 'no info_hash selected' by default?
- If each file has only one info_hash, why having a selector at all? Is there a case where several info_hashes can be found in a single file?

**Comment by csasm** [comment]
Because if you load any pcap file it may contain more than one infohashes. So in that case select option must be selected.

**Comment by rauljim** [comment]
OK, I see.
Can you select the first info_hash by default so the information loads immediately when the user selects a file? Is that easy to change?

**Comment by csasm** [comment]
First infohash pair is selected when it is browsed in new updated

**Comment by rauljim** [comment]
Great. It looks much nicer now.
