### ISSUE TITLE
Graphical visualization: log_distance grid

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#30]
Numbers and the nodes are not aligned on the grid. This is a critical issue.

**Comment by csasm** [comment]
I could not understand which grid?

**Comment by rauljim** [comment]
The log_distance numbers are not aligned with the circles in the lookup visualization. At least, not on my screen.
http://people.kth.se/~rauljc/pymdht/grid.png

**Comment by csasm** [comment]
They are now aligned to the grid, please check and confirm

**Comment by rauljim** [comment]
OK, have you tried with white background for the numbers? I see gray background.
