### ISSUE TITLE
Graphical visualization: no action on the grid

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#34]
If I open 20111118100028.out (I sent it by mail), set 'slow motion' to '10' and hit 'play' this is what I get:
- everything goes apparently well until second 0.74\* (I didn't look in details) other than the fact that there are red circles which shouldn't be there (but that's another open issue)
- From second 2.00 to second 2.7, the clock jumps a few times (I understand that every 'jump' represents an event) but there is no action on the grid. Why is that so?
- When I click 'pause' on second 0.74, the clock continues to second 2.00, and then pauses. This must not happen. If I click 'pause' I mean 'pause right now'.
  This also happens if I hit 'pause' and 'stop' quickly.
  Btw, why is 'stop' disabled during the visualization?

**Comment by csasm** [comment]
I would look at that

**Comment by csasm** [comment]
The jumping of clock was due to factor that it was trying to display the red nodes (which were already there, the ones that display at 0.74 seconds) but now as the timeout problem has been solved, so is this problem solved.Please check with the latest push

**Comment by rauljim** [comment]
I see what you say. I also see another event that is not represented on the grid: nodes with unknown log_distance. I open a new issue for that.
