### ISSUE TITLE
Graphical visualization: nodes with unknown log_distance

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#37]
The lookup is bootstrapped with nodes from the internal routing table. The visualization tool does not have access to that internal routing table, thus the id of these nodes is unknown until the nodes reply. In the case of a timeout, the id or the node remains unknown.

In 20111118100028.out, this happens with the query number 4.

As previously discussed, a simple solution would be to have an extra '?' column at the left end of the grid where these nodes can be represented.
This is important because the lack of this current visualization misleads the user. In 20111118100028.out, for instance, it seems that there are 3 parallel queries for the first 2 seconds, while in fact there are 4.

**Comment by rauljim** [comment]
I find very useful to use the 'next' and 'previous' bottoms. Ideally, for every click on 'next' some should change on the grid.

**Comment by csasm** [comment]
This issue has been solved in latest version, pull, check and comment
